
import java.awt.Color;
import java.awt.Component;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author GT
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form Game
     */
    Controller controller;
    int col_count;
    int row_count;

    public View(int r, int c) {
        this.col_count=c;
        this.row_count=r;
        Object[][] m= new String[col_count][row_count];
        Object[] a=new String[col_count];
        for(int i=0;i<col_count;i++){
            a[i]="";
            for(int j=0;j<row_count;j++){
                m[i][j]="0";
            }
        }
  

        initComponents();


        jTable1.setModel(new javax.swing.table.DefaultTableModel(m,a));
          jTable1.setRowHeight(jScrollPane1.getHeight()/row_count);
          YourTableCellRenderer cr = new YourTableCellRenderer();

        jTable1.setDefaultRenderer(Object.class, cr);

        
    }

    //Model model = new Model();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(100, 100));

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, "", "", "", null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "", "", "", "", "", "", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.setRowHeight(50);
        jTable1.setRowSelectionAllowed(false);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        jTable1.setVerifyInputWhenFocusTarget(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Игра \"Жизнь\"");

        jButton1.setText("Старт");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Стоп");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Расположение клеток первого поколения");

        jButton3.setText("Квадрат");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Шахматная доска");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Снежинка");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Паук");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Правила игры");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(301, 301, 301))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton7)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(jButton6))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5)
                            .addComponent(jButton3))))
                .addGap(18, 18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int Row = jTable1.getSelectedRow();
        int Column = jTable1.getSelectedColumn();
        if ("1".equals(jTable1.getValueAt(Row, Column))) {
            jTable1.setValueAt("0", Row, Column);

        } else {
            jTable1.setValueAt("1", Row, Column);

        }

        YourTableCellRenderer cr = new YourTableCellRenderer();

        jTable1.setDefaultRenderer(Object.class, cr);


    }//GEN-LAST:event_jTable1MouseClicked

    //Квадрат-закрашиваем первое поколение клеток
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        for (int i = 0; i < jTable1.getRowCount(); i++) {
            for (int j = 0; j < jTable1.getRowCount(); j++) {
                jTable1.setValueAt("0", i, j);
            }
        }

        for (int i = 3; i <= 4; i++) {
            for (int j = 3; j <= 4; j++) {
                jTable1.setValueAt("1", i, j);
            }
        }

        YourTableCellRenderer cr = new YourTableCellRenderer();
        jTable1.setDefaultRenderer(Object.class, cr);

    }//GEN-LAST:event_jButton3ActionPerformed

    //Шахматная доска-первое поколение клеток
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        for (int i = 0; i < jTable1.getRowCount(); i++) {
            for (int j = 0; j < jTable1.getRowCount(); j++) {
                jTable1.setValueAt("0", i, j);
            }
        }

        for (int i = 0; i < jTable1.getRowCount(); i++) {
            if (i % 2 == 0) {
                for (int j = 0; j < jTable1.getColumnCount(); j += 2) {
                    jTable1.setValueAt("1", i, j);

                }
            } else {
                for (int j = 1; j < jTable1.getColumnCount(); j += 2) {
                    jTable1.setValueAt("1", i, j);

                }
            }
        }

        YourTableCellRenderer cr = new YourTableCellRenderer();
        jTable1.setDefaultRenderer(Object.class, cr);

    }//GEN-LAST:event_jButton4ActionPerformed

    //Снежинки-первое поколение клеток
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        for (int i = 0; i < jTable1.getRowCount(); i++) {
            for (int j = 0; j < jTable1.getRowCount(); j++) {
                jTable1.setValueAt("0", i, j);
            }
        }

        for (int j = 0; j < jTable1.getColumnCount() - 1; j += 3) {
            jTable1.setValueAt("1", 0, j);
            jTable1.setValueAt("1", 6, j);
        }

        for (int j = 1; j < 6; j += 2) {
            jTable1.setValueAt("1", 1, j);
            jTable1.setValueAt("1", 5, j);
        }

        for (int j = 2; j < 5; j++) {
            jTable1.setValueAt("1", 2, j);
            jTable1.setValueAt("1", 4, j);
        }

        for (int j = 0; j < 7; j++) {
            if (j != 3) {
                jTable1.setValueAt("1", 3, j);
            }
        }

        YourTableCellRenderer cr = new YourTableCellRenderer();
        jTable1.setDefaultRenderer(Object.class, cr);


    }//GEN-LAST:event_jButton5ActionPerformed

    //Паук-первое поколение клеток
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        for (int i = 0; i < jTable1.getRowCount(); i++) {
            for (int j = 0; j < jTable1.getRowCount(); j++) {
                jTable1.setValueAt("0", i, j);
            }
        }

        jTable1.setValueAt("1", 0, 0);
        jTable1.setValueAt("1", 0, 6);

        for (int j = 1; j < 6; j += 2) {
            jTable1.setValueAt("1", 1, j);
        }

        for (int j = 2; j < 5; j++) {
            jTable1.setValueAt("1", 2, j);
            jTable1.setValueAt("1", 4, j);

        }

        for (int j = 0; j < 7; j++) {
            jTable1.setValueAt("1", 3, j);
        }

        for (int j = 1; j < 6; j++) {
            if (j != 3) {
                jTable1.setValueAt("1", 5, j);
            }
        }

        for (int j = 1; j < 6; j += 4) {
            jTable1.setValueAt("1", 6, j);
            jTable1.setValueAt("1", 7, j);

        }

        YourTableCellRenderer cr = new YourTableCellRenderer();
        jTable1.setDefaultRenderer(Object.class, cr);

    }//GEN-LAST:event_jButton6ActionPerformed

    //Показать правила
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
//        Model model = new Model();
        //model.showRules();
        controller.showRules();
    }//GEN-LAST:event_jButton7ActionPerformed

    //Пуск игры
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

       
        try {
            controller.startGame(jTable1);
        } catch (InterruptedException ex) {
           
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    //Стоп игры
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        controller.stopGame();

    }//GEN-LAST:event_jButton2ActionPerformed

    public void update(Integer[][] field) {

        for (int i = 0; i < field.length; i++) {
            for (int j = 0; j < field.length; j++) {

               String str = Integer.toString(field[i][j]);
                jTable1.setValueAt(str, i, j);

               
            }
        }
       
        YourTableCellRenderer cr = new YourTableCellRenderer();
        jTable1.setDefaultRenderer(Object.class, cr);

    }

    public JTable getjTable1() {
        return jTable1;
    }

    public class YourTableCellRenderer
            extends DefaultTableCellRenderer {

//        int col1;
//        int row1;
//
//        YourTableCellRenderer(int Row, int Col) {
//            this.row1 = Row;
//            this.col1 = Col;
//
//        }
        public Component getTableCellRendererComponent(JTable table,
                Object value,
                boolean isSelected,
                boolean hasFocus,
                int row,
                int column) {
            Component c
                    = super.getTableCellRendererComponent(table, value,
                            isSelected, hasFocus,
                            row, column);

            if ("1".equals(table.getModel().getValueAt(row, column))) {

                c.setBackground(Color.red);
                c.setForeground(Color.red);
                

            } else {
                c.setBackground(Color.white);
                c.setForeground(Color.white );
            }
            return c;
        }
    }

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//*/
//        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form 
//                View view = new View();
                this.setVisible(true);

//                Model model = new Model();
                Controller controller = new Controller(this);
            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
